export const INVENTORY_CATALOG_LIMIT = 1000
export const PROFILE_SELECT_LIMIT = 500
export const USER_HISTORY_LIMIT = 50
export const ADMIN_REQUESTS_LIMIT = 100
export const ADMIN_HISTORY_LIMIT = 100
export const DASHBOARD_LOW_STOCK_LIMIT = 6
export const DASHBOARD_RECENT_LOANS_LIMIT = 8
